# Site settings
title: Just ZoOL
email: zhooul@gmail.com
description: my blog for share
baseurl: ""
url: "http://foxzool.github.io"
twitter_username: foxzool
github_username: foxzool

# Build settings
markdown: redcarpet
permalink: pretty

paginate: 5

# github: [Repository metadata]

gems:
   - jekyll-sitemap

# tag_page_layout: tag_page
# tag_page_dir: tag

include:
  - .nojekyll

exclude:
  - "bower_components"
  - "bower.json"